lista_musicas/urls.py
from django.contrib import admin
from django.urls import path, include
import track.urls
from track.api import api


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(track.urls)),
    path("api/", api.urls)
]

track/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

track/models.py
from django.db import models

# Create your models here.

class Track(models.Model):
   id = models.AutoField(primary_key=True)
   title = models.CharField(max_length=20)
   artist = models.CharField(max_length=50)
   duration = models.FloatField()
   last_play = models.DateTimeField()

   def __str__(self):
      return self.title

track/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
   return render(request, "track/index.html")

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <script src="//unpkg.com/alpinejs" defer></script>
   <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
   <title>Simple CRUD</title>
</head>

<body>
   {% block content %}{% endblock content %}
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
   <script src="{% static "js/api.js" %}"></script>
</body>

</html>

track/templates/track/index.html
{% extends "base.html" %}

{% block content %}

<div x-data="appData()">
   <!-- Modal -->
   <div class="modal fade" id="myModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
               <label for="title">Title</label>
               <input id="id_title" name="title" class="form-control" type="text" required x-model="editItem.title">
               <label for="artist">Artist</label>
               <input id="id_artist" name="artist" class="form-control" type="text" required x-model="editItem.artist">
               <label for="last_play">Last Play</label>
               <input id="id_last_play" name="last_play" class="form-control" required type="datetime-local" x-model="editItem.last_play">
               <label for="duration">Duration</label>
               <input id="id_duration" name="duration" class="form-control" type="number" required x-model="editItem.duration">
            </div>
            <div class="modal-footer">
               <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
               <button type="button" class="btn btn-primary" data-bs-dismiss="modal" @click="saveData">Save
                  changes</button>
            </div>
         </div>
      </div>
   </div>
   <!--EndModal-->

   <!-- Edit Modal -->
   <div class="modal fade" id="myEditModal" tabindex="-1" aria-labelledby="exampleEditModalLabel" aria-hidden="true">
      <div class="modal-dialog">
         <div class="modal-content">
            <div class="modal-header">
               <h1 class="modal-title fs-5" id="exampleEditModalLabel">Edit Track</h1>
               <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form @submit.prevent="updateData()" x-show="!addMode">
               <div class="modal-body">
                  <label for="title">Title</label>
                  <input id="id_title" name="title" class="form-control" type="text" required x-model="form.title">
                  <label for="artist">Artist</label>
                  <input id="id_artist" name="artist" class="form-control" type="text" required x-model="form.artist">
                  <label for="last_play">Last Play</label>
                  <input id="id_last_play" name="last_play" class="form-control" required type="datetime-local" x-model="form.last_play">
                  <label for="duration">Duration</label>
                  <input id="id_duration" name="duration" class="form-control" type="number" required x-model="form.duration">
               </div>
               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                  <button type="submit" class="btn btn-primary">Atualizar</button>
               </div>
            </form>
         </div>
      </div>
   </div>
   <!--EndModal-->

   <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
      <h2>Lista de Musicas</h2>
   </div>

   <div class="d-flex flex-column flex-md-row align-items-center justify-content-center">
      <!--Modal-->
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myModal">
         Adicionar
      </button>
   </div>

   <div class="d-flex flex-column flex-md-row p-3 gap-3 py-md-3 align-items-center justify-content-center">
      <div class="list-group">
         <template x-for="(track, id) in tracks" :key="track.id">
            <a href="#" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
               <img src="https://www.svgrepo.com/show/530388/headphones-music.svg" alt="twbs" width="32" height="32" class="rounded-circle flex-shrink-0">
               <div class="d-flex gap-2 w-100 justify-content-between">
                  <div>
                     <strong class="mb-0">Title:</strong> <span x-text="track.title"></span><br>
                     <strong>Artist:</strong> <span class="mb-0 opacity-75" x-text="track.artist"></span><br>
                     <strong>Duration:</strong> <span class="mb-0 opacity-75" x-text="track.duration"></span><br>
                     <strong>Last Play:</strong> <span class="mb-0 opacity-75" x-text="track.last_play"></span><br>
                     <div class="container text-center">
                        <div class="row align-items-center justify-content-center">
                           <div class="col-auto">
                              <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#myEditModal" @click="editTrack(track)">Alterar</button>
                              <button type="button" class="btn btn-danger" aria-label="Close" @click="deleteItem(track)">Remover</button>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </a>
         </template>
      </div>
   </div>
</div>

{% endblock content %}